<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LP387" failures="1" tests="4" name="Default test" time="30.305" errors="0" timestamp="21 May 2024 14:06:03 GMT">
  <testcase classname="com.sample.tests.NegativeTest" name="checkInvalidqty" time="6.032"/>
  <testcase classname="com.sample.tests.NegativeTest" name="checkMissingName" time="5.888"/>
  <testcase classname="com.sample.tests.NegativeTest" name="checkMissingPhoneNum" time="5.733">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Missing phone number] but found [Thank you for your order! TOTAL: 9.75 Medium 8 Slices - 2 toppings]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Missing phone number] but found [Thank you for your order! TOTAL: 9.75 Medium 8 Slices - 2 toppings]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sample.tests.NegativeTest.checkMissingPhoneNum(NegativeTest.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- checkMissingPhoneNum -->
  <testcase classname="com.sample.tests.NegativeTest" name="checkresetbtn" time="8.234"/>
</testsuite> <!-- Default test -->
